# Generated by Django 4.2.1 on 2023-05-04 13:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('status', models.CharField()),
                ('from_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_from_request', to=settings.AUTH_USER_MODEL)),
                ('to_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_to_request', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
