# Generated by Django 4.2.1 on 2023-05-04 14:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0002_remove_friendrequest_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequest',
            name='answered_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
