# Generated by Django 4.2.1 on 2023-05-04 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0003_friendrequest_answered_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequest',
            name='answered_on',
            field=models.DateTimeField(null=True),
        ),
    ]
